### ISSUE TITLE
problem in instalation: Getting requirements to build wheel did not run successfully.

### ISSUE THREAD

**Issue by jishnuthewalker** [cubiq/ComfyUI_InstantID#171]
## Execute install/(de)activation script for 'D:\my_stuff\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID'
 Collecting insightface
   Using cached insightface-0.7.3.tar.gz (439 kB)
   Installing build dependencies: started
   Installing build dependencies: finished with status 'done'
   Getting requirements to build wheel: started
   Getting requirements to build wheel: finished with status 'error'
[!]   error: subprocess-exited-with-error
[!]
[!]   Getting requirements to build wheel did not run successfully.
[!]   exit code: 1
[!]
[!]   [18 lines of output]
[!]   Traceback (most recent call last):
[!]     File "D:\my_stuff\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
[!]       main()
[!]     File "D:\my_stuff\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
[!]       json_out['return_val'] = hook(**hook_input['kwargs'])
[!]                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "D:\my_stuff\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
[!]       return hook(config_settings)
[!]              ^^^^^^^^^^^^^^^^^^^^^
[!]     File "D:\my_stuff\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
[!]       return self._get_build_requires(config_settings, requirements=['wheel'])
[!]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "D:\my_stuff\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
[!]       self.run_setup()
[!]     File "D:\my_stuff\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
[!]       exec(code, locals())
[!]     File "<string>", line 11, in <module>
[!]   ModuleNotFoundError: No module named 'Cython'
[!]   [end of output]
[!]
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
[!] error: subprocess-exited-with-error
[!]
[!] Getting requirements to build wheel did not run successfully.
[!] exit code: 1
[!]
[!] See above for output.
[!]
[!] note: This error originates from a subprocess, and is likely not a problem with pip.
install/(de)activation script failed: D:\my_stuff\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID

[ComfyUI-Manager] Startup script completed.
#######################################################################

not sure what to do with this

**Comment by jishnuthewalker** [comment]
nvm i found a solution in a previous issue. i love the internet.

[https://github.com/cubiq/ComfyUI_InstantID/issues/161#issuecomment-2127346963](https://github.com/cubiq/ComfyUI_InstantID/issues/161#issuecomment-2127346963)
