### ISSUE TITLE
ERROR, 

### ISSUE THREAD

**Issue by 37OMKAR** [cubiq/ComfyUI_InstantID#199]
Prompt executed in 13.73 seconds
got prompt
[rgthree] Using rgthree's optimized recursive execution.
download_path: F:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\models\insightface\models\antelopev2
Downloading F:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\models\insightface\models\antelopev2.zip from https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip...
!!! Exception during processing!!! Failed downloading url https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip
Traceback (most recent call last):
  File "F:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI_InstantID\InstantID.py", line 217, in load_insight_face
    model = FaceAnalysis(name="antelopev2", root=INSIGHTFACE_DIR, providers=[provider + 'ExecutionProvider',]) # alternative to buffalo_l
  File "F:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\insightface\app\face_analysis.py", line 27, in __init__
    self.model_dir = ensure_available('models', name, root=root)
  File "F:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\insightface\utils\storage.py", line 28, in ensure_available
    return download(sub_dir, name, force=False, root=root)
  File "F:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\insightface\utils\storage.py", line 17, in download
    download_file(model_url,
  File "F:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\insightface\utils\download.py", line 73, in download_file
    raise RuntimeError("Failed downloading url %s" % url)
RuntimeError: Failed downloading url https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip

**Comment by NotTheD** [comment]
Has same problem. 

Solution woked for me (found in README.MD file in \custom_nodes\ComfyUI_InstantID):
1.Download the models (for example from here: https://drive.google.com/file/d/18wEUfMNohBJ4K3Ly5wpTejPfDzp-8fI8/view?usp=sharing or here: https://huggingface.co/MonsterMMORPG/tools/tree/main   [ both links are works, I download from huggingface]
2. Unzip and place them in the `ComfyUI/models/insightface/models/antelopev2` directory.  ! VERY IMPORTANT ! EXACTLY TO NOTED PATH. If some folder missing - create it
3. Restart ComfyUI.
4. Done!

**Comment by migandhi** [comment]
![insightface](https://github.com/user-attachments/assets/751e1c82-0052-479c-8927-8df773d04d9f)
I installed the models from manager
