### ISSUE TITLE
Cannot install Instantid from ComfyUI

### ISSUE THREAD

**Issue by Malzu22** [cubiq/ComfyUI_InstantID#213]
keep getting this error and I cannot bypass it

![ComfyUI](https://github.com/user-attachments/assets/4c6f5b0f-34dd-452f-b020-dc20630e89a2)

**Comment by cubiq** [comment]
it's impossible to say without a full error report

**Comment by Ultimo89** [comment]
> it's impossible to say without a full error report

I cubiq, first of all, thank you for your work! I have the same problem reported above, here the full error report:

```
Restarting... [Legacy Mode]


[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-09-12 17:50:39.529265
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: D:\ComfyUI\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI
** Log path: D:\ComfyUI\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   1.9 seconds: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 6144 MB, total RAM 16331 MB
pytorch version: 2.4.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1660 SUPER : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\web
D:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
### Loading: ComfyUI-Manager (V2.50.3)
### ComfyUI Revision: 2683 [b962db99] | Released on '2024-09-12'

Import times for custom nodes:
   0.0 seconds: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.1 seconds: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.4 seconds: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
FETCH DATA from: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]
FETCH DATA from: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json [DONE]
FETCH DATA from: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\746607195_github-stats.json [DONE]
FETCH DATA from: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\custom-node-list.json [DONE]
FETCH DATA from: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1241942342_custom-node-list.json [DONE]
Install custom node 'ComfyUI InstantID (Native Support)'
Install: ['https://github.com/cubiq/ComfyUI_InstantID']
Download: git clone 'https://github.com/cubiq/ComfyUI_InstantID'
[!]
100%|██████████| 68.0/68.0 [00:01<00:00, 65.60it/s]
100%|██████████| 68.0/68.0 [00:01<00:00, 65.60it/s]
100%|██████████| 34.0/34.0 [00:01<00:00, 32.69it/s]
100%|██████████| 34.0/34.0 [00:01<00:00, 32.69it/s]
100%|██████████| 163.0/163.0 [00:01<00:00, 128.69it/s]
100%|██████████| 163.0/163.0 [00:01<00:00, 128.69it/s]
100%|██████████| 92.0/92.0 [00:01<00:00, 72.04it/s]
100%|██████████| 92.0/92.0 [00:01<00:00, 72.04it/s]
100%|██████████| 92.0/92.0 [00:02<00:00, 38.49it/s]
Install: pip packages
Installation was successful.
After restarting ComfyUI, please refresh the browser.

Restarting... [Legacy Mode]


[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-09-12 17:51:42.452127
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: D:\ComfyUI\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI
** Log path: D:\ComfyUI\ComfyUI_windows_portable\comfyui.log

#######################################################################
[ComfyUI-Manager] Starting dependency installation/(de)activation for the extension


## ComfyUI-Manager: EXECUTE => ['D:\\ComfyUI\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', 'insightface']

## Execute install/(de)activation script for 'D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID'
 Collecting insightface
   Using cached insightface-0.7.3.tar.gz (439 kB)
   Installing build dependencies: started
   Installing build dependencies: finished with status 'done'
   Getting requirements to build wheel: started
   Getting requirements to build wheel: finished with status 'error'
[!]   error: subprocess-exited-with-error
[!]
[!]   Getting requirements to build wheel did not run successfully.
[!]   exit code: 1
[!]
[!]   [18 lines of output]
[!]   Traceback (most recent call last):
[!]     File "D:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
[!]       main()
[!]     File "D:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
[!]       json_out['return_val'] = hook(**hook_input['kwargs'])
[!]                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "D:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
[!]       return hook(config_settings)
[!]              ^^^^^^^^^^^^^^^^^^^^^
[!]     File "D:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
[!]       return self._get_build_requires(config_settings, requirements=[])
[!]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "D:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
[!]       self.run_setup()
[!]     File "D:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
[!]       exec(code, locals())
[!]     File "<string>", line 11, in <module>
[!]   ModuleNotFoundError: No module named 'Cython'
[!]   [end of output]
[!]
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
[!] error: subprocess-exited-with-error
[!]
[!] Getting requirements to build wheel did not run successfully.
[!] exit code: 1
[!]
[!] See above for output.
[!]
[!] note: This error originates from a subprocess, and is likely not a problem with pip.
install/(de)activation script failed: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID

[ComfyUI-Manager] Startup script completed.
#######################################################################


Prestartup times for custom nodes:
  27.7 seconds: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 6144 MB, total RAM 16331 MB
pytorch version: 2.4.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1660 SUPER : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\web
D:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
### Loading: ComfyUI-Manager (V2.50.3)
### ComfyUI Revision: 2683 [b962db99] | Released on '2024-09-12'
Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID\__init__.py", line 1, in <module>
    from .InstantID import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID\InstantID.py", line 7, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

Cannot import D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID module for custom nodes: No module named 'cv2'

Import times for custom nodes:
   0.0 seconds: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds (IMPORT FAILED): D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID
   0.0 seconds: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.4 seconds: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
FETCH DATA from: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]
FETCH DATA from: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json [DONE]
FETCH DATA from: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\746607195_github-stats.json [DONE]
```

**Comment by cubiq** [comment]
you probably need to install 'opencv-python'

**Comment by Ultimo89** [comment]
I installed “opencv-pyton” in version 4.10.0.84 as suggested, uninstalled and tried reinstalling the custom node, but the error remains.
I am sending the log again in case it is needed.
```
[START] Security scan

D:\ComfyUI\ComfyUI_windows_portable>pause
Premere un tasto per continuare . . . [DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-09-12 19:55:40.697750
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: D:\ComfyUI\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI
** Log path: D:\ComfyUI\ComfyUI_windows_portable\comfyui.log

#######################################################################
[ComfyUI-Manager] Starting dependency installation/(de)activation for the extension


## ComfyUI-Manager: EXECUTE => ['D:\\ComfyUI\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', 'insightface']

## Execute install/(de)activation script for 'D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID'
 Collecting insightface
   Using cached insightface-0.7.3.tar.gz (439 kB)
   Installing build dependencies: started
   Installing build dependencies: finished with status 'done'
   Getting requirements to build wheel: started
   Getting requirements to build wheel: finished with status 'error'
[!]   error: subprocess-exited-with-error
[!]
[!]   Getting requirements to build wheel did not run successfully.
[!]   exit code: 1
[!]
[!]   [18 lines of output]
[!]   Traceback (most recent call last):
[!]     File "D:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
[!]       main()
[!]     File "D:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
[!]       json_out['return_val'] = hook(**hook_input['kwargs'])
[!]                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "D:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
[!]       return hook(config_settings)
[!]              ^^^^^^^^^^^^^^^^^^^^^
[!]     File "D:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
[!]       return self._get_build_requires(config_settings, requirements=[])
[!]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "D:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
[!]       self.run_setup()
[!]     File "D:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
[!]       exec(code, locals())
[!]     File "<string>", line 11, in <module>
[!]   ModuleNotFoundError: No module named 'Cython'
[!]   [end of output]
[!]
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
[!] error: subprocess-exited-with-error
[!]
[!] Getting requirements to build wheel did not run successfully.
[!] exit code: 1
[!]
[!] See above for output.
[!]
[!] note: This error originates from a subprocess, and is likely not a problem with pip.
install/(de)activation script failed: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID

[ComfyUI-Manager] Startup script completed.
#######################################################################


Prestartup times for custom nodes:
  27.4 seconds: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 6144 MB, total RAM 16331 MB
pytorch version: 2.4.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1660 SUPER : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\web
D:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
### Loading: ComfyUI-Manager (V2.50.3)
### ComfyUI Revision: 2683 [b962db99] | Released on '2024-09-12'
Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID\__init__.py", line 1, in <module>
    from .InstantID import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID\InstantID.py", line 7, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

Cannot import D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID module for custom nodes: No module named 'cv2'

Import times for custom nodes:
   0.0 seconds: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds (IMPORT FAILED): D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID
   0.0 seconds: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.4 seconds: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH DATA from: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
FETCH DATA from: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]
FETCH DATA from: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json [DONE]
FETCH DATA from: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\746607195_github-stats.json [DONE]
```

**Comment by CHINAGRIMACE** [comment]
## ComfyUI-Manager: EXECUTE => ['/Users/bucongming/Desktop/ComfyUI/venv/bin/python', '-m', 'pip', 'install', 'onnxruntime-gpu']
[! ] WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)'))': /simple/onnxruntime-gpu/
[! ] WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)'))': /simple/onnxruntime-gpu/
[! ] WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)'))': /simple/onnxruntime-gpu/
[! ] WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)'))': /simple/onnxruntime-gpu/
[! ] WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)'))': /simple/onnxruntime-gpu/
Could not fetch URL https://pypi.org/simple/onnxruntime-gpu/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/onnxruntime-gpu/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)'))) - skipping
[! ] ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu (from versions: none)
[! ] ERROR: No matching distribution found for onnxruntime-gpu
install script failed: https://github.com/cubiq/ComfyUI_InstantID
Attempt to fixing '['https://github.com/cubiq/ComfyUI_InstantID']' is done.

## ComfyUI-Manager: EXECUTE => ['/Users/bucongming/Desktop/ComfyUI/venv/bin/python', '-m', 'pip', 'install', 'numpy<2']
After restarting ComfyUI, please refresh the browser.

同样遇到这个问题，每次终端会显示这个信息，用的是Mac
![CleanShot 2024-09-26 at 00 18 08@2x](https://github.com/user-attachments/assets/8d992242-75ee-432d-9c9c-4db3d7ab3c15)
![CleanShot 2024-09-26 at 00 17 48@2x](https://github.com/user-attachments/assets/322ed3c8-2d20-4dd0-937d-46d67c62587a)

**Comment by kldkn** [comment]
me too
