### ISSUE TITLE
 动态链接库(DLL)初始化例程失败。

### ISSUE THREAD

**Issue by cxpic** [cubiq/ComfyUI_InstantID#215]
[32m ** Comfly Loaded :[33m fly, just fly[0m
Traceback (most recent call last):
  File "E:\ccoo\ai\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ccoo\ai\ComfyUI\custom_nodes\ComfyUI_InstantID\__init__.py", line 1, in <module>
    from .InstantID import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "E:\ccoo\ai\ComfyUI\custom_nodes\ComfyUI_InstantID\InstantID.py", line 13, in <module>
    from insightface.app import FaceAnalysis
  File "E:\ccoo\ai\ComfyUI\.ext\Lib\site-packages\insightface\__init__.py", line 16, in <module>
    from . import model_zoo
  File "E:\ccoo\ai\ComfyUI\.ext\Lib\site-packages\insightface\model_zoo\__init__.py", line 1, in <module>
    from .model_zoo import get_model
  File "E:\ccoo\ai\ComfyUI\.ext\Lib\site-packages\insightface\model_zoo\model_zoo.py", line 11, in <module>
    from .arcface_onnx import *
  File "E:\ccoo\ai\ComfyUI\.ext\Lib\site-packages\insightface\model_zoo\arcface_onnx.py", line 10, in <module>
    import onnx
  File "E:\ccoo\ai\ComfyUI\.ext\Lib\site-packages\onnx\__init__.py", line 77, in <module>
    from onnx.onnx_cpp2py_export import ONNX_ML
ImportError: DLL load failed while importing onnx_cpp2py_export: 动态链接库(DLL)初始化例程失败。

Cannot import E:\ccoo\ai\ComfyUI\custom_nodes\ComfyUI_InstantID module for custom nodes: DLL load failed while importing onnx_cpp2py_export: 动态链接库(DLL)初始化例程失败。

**Comment by delcompan** [comment]
same problem

**Comment by gaoming714** [comment]
> Onnx version problem, uninstall version 1.16.2 python -m pip install onnx==1.16.1

it woks ，why？

**Comment by cxpic** [comment]
> onnx 版本问题，卸载 1.16.2 版本 python -m pip install onnx==1.16.1

我换过1.16.1还是错的
