### ISSUE TITLE
当我在InstantlD Face Analysis节点使用CUDA时报错，而使用cpu和ROCM均可运行

### ISSUE THREAD

**Issue by weichanglang** [cubiq/ComfyUI_InstantID#216]
File "D:\B\ComfyUI\custom_nodes\ComfyUI_InstantID\InstantID.py", line 217, in load_insight_face
    model = FaceAnalysis(name="antelopev2", root=INSIGHTFACE_DIR, providers=[provider + 'ExecutionProvider',]) # alternative to buffalo_l
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\A\Anaconda3\envs\BAD\Lib\site-packages\insightface\app\face_analysis.py", line 31, in __init__
    model = model_zoo.get_model(onnx_file, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\A\Anaconda3\envs\BAD\Lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
    model = router.get_model(providers=providers, provider_options=provider_options)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\A\Anaconda3\envs\BAD\Lib\site-packages\insightface\model_zoo\model_zoo.py", line 40, in get_model
    session = PickableInferenceSession(self.onnx_file, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\A\Anaconda3\envs\BAD\Lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
  File "D:\A\Anaconda3\envs\BAD\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 394, in __init__
    raise fallback_error from e
  File "D:\A\Anaconda3\envs\BAD\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 389, in __init__
    self._create_inference_session(self._fallback_providers, None)
  File "D:\A\Anaconda3\envs\BAD\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 435, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:636 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.

** Python version: 3.11.9 | packaged by Anaconda, Inc. | (main, Apr 19 2024, 16:40:41) [MSC v.1916 64 bit (AMD64)]
** Python executable: D:\A\Anaconda3\envs\BAD\python.exe
** ComfyUI Path: D:\B\ComfyUI
** Log path: D:\B\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: D:\B\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: D:\B\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   1.2 seconds: D:\B\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 16380 MB, total RAM 32581 MB
pytorch version: 2.4.1+cu124

**Comment by iazkaban** [comment]
我的是所有的这个选项都报错


# ComfyUI Error Report
## Error Details
- **Node Type:** InstantIDFaceAnalysis
- **Exception Type:** AssertionError
- **Exception Message:** 
## Stack Trace
```
  File "P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID\InstantID.py", line 217, in load_insight_face
    model = FaceAnalysis(name="antelopev2", root=INSIGHTFACE_DIR, providers=[provider + 'ExecutionProvider',]) # alternative to buffalo_l
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "P:\sd-webui-aki\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
           ^^^^^^^^^^^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.2.4-2-g915fdb5
- **Arguments:** P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\main.py --auto-launch --preview-method auto --disable-cuda-malloc --fast
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.5.0+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 25756565504
  - **VRAM Free:** 22377736184
  - **Torch VRAM Total:** 1677721600
  - **Torch VRAM Free:** 32581624

## Logs
```
2024-10-23 11:38:29,421 - root - INFO - Total VRAM 24563 MB, total RAM 65313 MB
2024-10-23 11:38:29,421 - root - INFO - pytorch version: 2.5.0+cu124
2024-10-23 11:38:29,421 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-23 11:38:29,421 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
2024-10-23 11:38:30,093 - root - INFO - Using pytorch cross attention
2024-10-23 11:38:30,879 - root - INFO - [Prompt Server] web root: P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\web
2024-10-23 11:38:30,880 - root - INFO - Adding extra search path checkpoints P:/sd-webui-aki/sd-webui-aki-v4\models/Stable-diffusion
2024-10-23 11:38:30,880 - root - INFO - Adding extra search path configs P:/sd-webui-aki/sd-webui-aki-v4\models/Stable-diffusion
2024-10-23 11:38:30,880 - root - INFO - Adding extra search path vae P:/sd-webui-aki/sd-webui-aki-v4\models/VAE
2024-10-23 11:38:30,880 - root - INFO - Adding extra search path loras P:/sd-webui-aki/sd-webui-aki-v4\models/Lora
2024-10-23 11:38:30,880 - root - INFO - Adding extra search path loras P:/sd-webui-aki/sd-webui-aki-v4\models/LyCORIS
2024-10-23 11:38:30,880 - root - INFO - Adding extra search path upscale_models P:/sd-webui-aki/sd-webui-aki-v4\models/ESRGAN
2024-10-23 11:38:30,880 - root - INFO - Adding extra search path upscale_models P:/sd-webui-aki/sd-webui-aki-v4\models/RealESRGAN
2024-10-23 11:38:30,880 - root - INFO - Adding extra search path upscale_models P:/sd-webui-aki/sd-webui-aki-v4\models/SwinIR
2024-10-23 11:38:30,880 - root - INFO - Adding extra search path embeddings P:/sd-webui-aki/sd-webui-aki-v4\embeddings
2024-10-23 11:38:30,880 - root - INFO - Adding extra search path hypernetworks P:/sd-webui-aki/sd-webui-aki-v4\models/hypernetworks
2024-10-23 11:38:30,880 - root - INFO - Adding extra search path controlnet P:/sd-webui-aki/sd-webui-aki-v4\models/ControlNet
2024-10-23 11:38:35,067 - root - INFO - 
Import times for custom nodes:
2024-10-23 11:38:35,067 - root - INFO -    0.0 seconds: P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-10-23 11:38:35,067 - root - INFO -    0.0 seconds: P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\custom_nodes\AIGODLIKE-COMFYUI-TRANSLATION
2024-10-23 11:38:35,067 - root - INFO -    0.0 seconds: P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-text-overlay
2024-10-23 11:38:35,067 - root - INFO -    0.0 seconds: P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-10-23 11:38:35,067 - root - INFO -    0.0 seconds: P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-10-23 11:38:35,067 - root - INFO -    0.1 seconds: P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools
2024-10-23 11:38:35,067 - root - INFO -    0.1 seconds: P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-dynamicprompts
2024-10-23 11:38:35,067 - root - INFO -    0.2 seconds: P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use
2024-10-23 11:38:35,067 - root - INFO -    0.2 seconds: P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-10-23 11:38:35,067 - root - INFO -    0.2 seconds: P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-10-23 11:38:35,067 - root - INFO -    0.3 seconds: P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Gemini
2024-10-23 11:38:35,067 - root - INFO -    0.6 seconds: P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID
2024-10-23 11:38:35,067 - root - INFO -    0.9 seconds: P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Text
2024-10-23 11:38:35,067 - root - INFO -    1.3 seconds: P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
2024-10-23 11:38:35,067 - root - INFO - 
2024-10-23 11:38:35,073 - root - INFO - Starting server

2024-10-23 11:38:35,073 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-10-23 11:44:16,700 - root - INFO - got prompt
2024-10-23 11:44:16,847 - root - INFO - model weight dtype torch.float16, manual cast: None
2024-10-23 11:44:16,848 - root - INFO - model_type EPS
2024-10-23 11:44:17,826 - root - INFO - Using pytorch attention in VAE
2024-10-23 11:44:17,826 - root - INFO - Using pytorch attention in VAE
2024-10-23 11:44:18,073 - root - INFO - Requested to load SDXLClipModel
2024-10-23 11:44:18,074 - root - INFO - Loading 1 new model
2024-10-23 11:44:18,080 - root - INFO - loaded completely 0.0 1560.802734375 True
2024-10-23 11:44:20,241 - root - ERROR - !!! Exception during processing !!! 
2024-10-23 11:44:20,242 - root - ERROR - Traceback (most recent call last):
  File "P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID\InstantID.py", line 217, in load_insight_face
    model = FaceAnalysis(name="antelopev2", root=INSIGHTFACE_DIR, providers=[provider + 'ExecutionProvider',]) # alternative to buffalo_l
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\sd-webui-aki\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

2024-10-23 11:44:20,242 - root - INFO - Prompt executed in 3.54 seconds
2024-10-23 11:44:27,432 - root - INFO - got prompt
2024-10-23 11:44:27,439 - root - ERROR - !!! Exception during processing !!! 
2024-10-23 11:44:27,441 - root - ERROR - Traceback (most recent call last):
  File "P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID\InstantID.py", line 217, in load_insight_face
    model = FaceAnalysis(name="antelopev2", root=INSIGHTFACE_DIR, providers=[provider + 'ExecutionProvider',]) # alternative to buffalo_l
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\sd-webui-aki\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

2024-10-23 11:44:27,441 - root - INFO - Prompt executed in 0.01 seconds
2024-10-23 11:44:33,042 - root - INFO - got prompt
2024-10-23 11:44:33,049 - root - ERROR - !!! Exception during processing !!! 
2024-10-23 11:44:33,050 - root - ERROR - Traceback (most recent call last):
  File "P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID\InstantID.py", line 217, in load_insight_face
    model = FaceAnalysis(name="antelopev2", root=INSIGHTFACE_DIR, providers=[provider + 'ExecutionProvider',]) # alternative to buffalo_l
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\sd-webui-aki\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

2024-10-23 11:44:33,050 - root - INFO - Prompt executed in 0.00 seconds
2024-10-23 11:44:38,264 - root - INFO - got prompt
2024-10-23 11:44:38,271 - root - ERROR - !!! Exception during processing !!! 
2024-10-23 11:44:38,272 - root - ERROR - Traceback (most recent call last):
  File "P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID\InstantID.py", line 217, in load_insight_face
    model = FaceAnalysis(name="antelopev2", root=INSIGHTFACE_DIR, providers=[provider + 'ExecutionProvider',]) # alternative to buffalo_l
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\sd-webui-aki\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

2024-10-23 11:44:38,274 - root - INFO - Prompt executed in 0.01 seconds
2024-10-23 11:44:46,807 - root - INFO - got prompt
2024-10-23 11:44:46,816 - root - ERROR - !!! Exception during processing !!! 
2024-10-23 11:44:46,817 - root - ERROR - Traceback (most recent call last):
  File "P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\sd-webui-aki\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID\InstantID.py", line 217, in load_insight_face
    model = FaceAnalysis(name="antelopev2", root=INSIGHTFACE_DIR, providers=[provider + 'ExecutionProvider',]) # alternative to buffalo_l
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\sd-webui-aki\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

2024-10-23 11:44:46,818 - root - INFO - Prompt executed in 0.01 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":66,"last_link_id":220,"nodes":[{"id":11,"type":"InstantIDModelLoader","pos":{"0":560,"1":70},"size":{"0":238.72393798828125,"1":58},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"INSTANTID","type":"INSTANTID","links":[197],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"InstantIDModelLoader"},"widgets_values":["ip-adapter.bin"]},{"id":15,"type":"PreviewImage","pos":{"0":1670,"1":300},"size":{"0":584.0855712890625,"1":610.4592895507812},"flags":{},"order":11,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":19,"label":"图像"}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"},"widgets_values":[]},{"id":5,"type":"EmptyLatentImage","pos":{"0":910,"1":540},"size":{"0":315,"1":106},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"LATENT","type":"LATENT","links":[2],"slot_index":0,"label":"Latent"}],"properties":{"Node name for S&R":"EmptyLatentImage"},"widgets_values":[1016,1016,1]},{"id":8,"type":"VAEDecode","pos":{"0":1670,"1":210},"size":{"0":210,"1":46},"flags":{},"order":10,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":7,"label":"Latent"},{"name":"vae","type":"VAE","link":8,"label":"VAE"}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[19],"slot_index":0,"label":"图像"}],"properties":{"Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":60,"type":"ApplyInstantID","pos":{"0":910,"1":210},"size":{"0":315,"1":266},"flags":{},"order":8,"mode":0,"inputs":[{"name":"instantid","type":"INSTANTID","link":197,"label":"InstantID"},{"name":"insightface","type":"FACEANALYSIS","link":198,"label":"InsightFace"},{"name":"control_net","type":"CONTROL_NET","link":199,"label":"ControlNet"},{"name":"image","type":"IMAGE","link":214,"label":"图像"},{"name":"model","type":"MODEL","link":206,"label":"模型"},{"name":"positive","type":"CONDITIONING","link":203,"label":"正面条件"},{"name":"negative","type":"CONDITIONING","link":204,"label":"负面条件"},{"name":"image_kps","type":"IMAGE","link":null,"shape":7,"label":"图像_kps"},{"name":"mask","type":"MASK","link":null,"shape":7,"label":"遮罩"}],"outputs":[{"name":"MODEL","type":"MODEL","links":[220],"slot_index":0,"shape":3,"label":"模型"},{"name":"positive","type":"CONDITIONING","links":[200],"slot_index":1,"shape":3,"label":"正面条件"},{"name":"negative","type":"CONDITIONING","links":[201],"slot_index":2,"shape":3,"label":"负面条件"}],"properties":{"Node name for S&R":"ApplyInstantID"},"widgets_values":[0.8,0,1]},{"id":39,"type":"CLIPTextEncode","pos":{"0":520,"1":430},"size":{"0":291.9967346191406,"1":128.62518310546875},"flags":{},"order":6,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":122,"label":"CLIP"}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[203],"slot_index":0,"shape":3,"label":"条件"}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["comic character. graphic illustration, comic art, graphic novel art, vibrant, highly detailed",true]},{"id":40,"type":"CLIPTextEncode","pos":{"0":520,"1":620},"size":{"0":286.3603515625,"1":112.35245513916016},"flags":{},"order":7,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":123,"label":"CLIP"}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[204],"slot_index":0,"shape":3,"label":"条件"}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["photograph, deformed, glitch, noisy, realistic, stock photo",true]},{"id":3,"type":"KSampler","pos":{"0":1300,"1":210},"size":{"0":315,"1":262},"flags":{},"order":9,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":220,"label":"模型"},{"name":"positive","type":"CONDITIONING","link":200,"label":"正面条件"},{"name":"negative","type":"CONDITIONING","link":201,"label":"负面条件"},{"name":"latent_image","type":"LATENT","link":2,"label":"Latent"}],"outputs":[{"name":"LATENT","type":"LATENT","links":[7],"slot_index":0,"label":"Latent"}],"properties":{"Node name for S&R":"KSampler"},"widgets_values":[1631591050,"fixed",30,4.5,"ddpm","karras",1]},{"id":4,"type":"CheckpointLoaderSimple","pos":{"0":70,"1":520},"size":{"0":315,"1":98},"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[206],"slot_index":0,"label":"模型"},{"name":"CLIP","type":"CLIP","links":[122,123],"slot_index":1,"label":"CLIP"},{"name":"VAE","type":"VAE","links":[8],"slot_index":2,"label":"VAE"}],"properties":{"Node name for S&R":"CheckpointLoaderSimple"},"widgets_values":["01真人\\albedobaseXL_v3Mini.safetensors"]},{"id":16,"type":"ControlNetLoader","pos":{"0":560,"1":290},"size":{"0":250.07241821289062,"1":58},"flags":{},"order":3,"mode":0,"inputs":[],"outputs":[{"name":"CONTROL_NET","type":"CONTROL_NET","links":[199],"slot_index":0,"shape":3,"label":"ControlNet"}],"properties":{"Node name for S&R":"ControlNetLoader"},"widgets_values":["diffusion_pytorch_model.safetensors"]},{"id":13,"type":"LoadImage","pos":{"0":290,"1":70},"size":{"0":210,"1":314},"flags":{},"order":4,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[214],"slot_index":0,"shape":3,"label":"图像"},{"name":"MASK","type":"MASK","links":null,"shape":3,"label":"遮罩"}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["ldh-1701779316060.jpg","image"]},{"id":38,"type":"InstantIDFaceAnalysis","pos":{"0":570,"1":180},"size":{"0":227.09793090820312,"1":58},"flags":{},"order":5,"mode":0,"inputs":[],"outputs":[{"name":"FACEANALYSIS","type":"FACEANALYSIS","links":[198],"slot_index":0,"shape":3,"label":"面部分析"}],"properties":{"Node name for S&R":"InstantIDFaceAnalysis"},"widgets_values":["CUDA"]}],"links":[[2,5,0,3,3,"LATENT"],[7,3,0,8,0,"LATENT"],[8,4,2,8,1,"VAE"],[19,8,0,15,0,"IMAGE"],[122,4,1,39,0,"CLIP"],[123,4,1,40,0,"CLIP"],[197,11,0,60,0,"INSTANTID"],[198,38,0,60,1,"FACEANALYSIS"],[199,16,0,60,2,"CONTROL_NET"],[200,60,1,3,1,"CONDITIONING"],[201,60,2,3,2,"CONDITIONING"],[203,39,0,60,5,"CONDITIONING"],[204,40,0,60,6,"CONDITIONING"],[206,4,0,60,4,"MODEL"],[214,13,0,60,3,"IMAGE"],[220,60,0,3,0,"MODEL"]],"groups":[],"config":{},"extra":{"ds":{"scale":1.0152559799477068,"offset":[148.5912209924284,343.18172094582667]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
