### ISSUE TITLE
Failed downloading insightface file

### ISSUE THREAD

**Issue by Eagle07-Sudo** [cubiq/ComfyUI_InstantID#22]
InstantID attempts to download the antelopev2.zip file into  ...\models\insightface\models using a link that leads to a _nonexistent error_.
I tried to use [the link](https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip) to download it directly, but it couldn't locate the file.
Then I used [this page](https://github.com/deepinsight/insightface/tree/master/python-package) to download it. After unzipping it, I pasted the folder into the specified location, and it is now working.
The issue is discussed [here](https://github.com/deepinsight/insightface/issues/2517).
```
download_path: C:\AI\ComfyUI_windows_portable\ComfyUI\models\insightface\models\antelopev2
Downloading C:\AI\ComfyUI_windows_portable\ComfyUI\models\insightface\models\antelopev2.zip from https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip...
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-0246\utils.py", line 372, in new_func
    res_value = old_func(*final_args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID\InstantID.py", line 359, in load_insight_face
    model = FaceAnalysis(name="antelopev2", root=INSIGHTFACE_DIR, providers=[provider + 'ExecutionProvider',]) # buffalo_l
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\face_analysis.py", line 27, in __init__
    self.model_dir = ensure_available('models', name, root=root)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\utils\storage.py", line 28, in ensure_available
    return download(sub_dir, name, force=False, root=root)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\utils\storage.py", line 17, in download
    download_file(model_url,
  File "C:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\utils\download.py", line 73, in download_file
    raise RuntimeError("Failed downloading url %s" % url)
RuntimeError: Failed downloading url https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip
```

**Comment by cubiq** [comment]
there are two links in the read me and instruction on where to put the models
