### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by mostfafathy94** [cubiq/ComfyUI_InstantID#230]
### ComfyUI Revision: 2758 [3c60ecd7] | Released on '2024-10-12'
Traceback (most recent call last):
  File "C:\Users\ahmed\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\nodes.py", line 2001, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\ahmed\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI_InstantID\__init__.py", line 1, in <module>
    from .InstantID import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Users\ahmed\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI_InstantID\InstantID.py", line 7, in <module>
    import cv2
![Uploading er.PNG…]()

Cannot import C:\Users\ahmed\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI_InstantID module for custom nodes: No module named 'cv2'

**Comment by ClothingAI** [comment]
solution?
