### ISSUE TITLE
Issue with newest Albumentations

### ISSUE THREAD

**Issue by EnragedAntelope** [cubiq/ComfyUI_InstantID#233]
With albumentations 1.4.19:

```
Traceback (most recent call last):
  File "D:\ComfyUI\nodes.py", line 2001, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\custom_nodes\ComfyUI_InstantID\__init__.py", line 1, in <module>
    from .InstantID import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI\custom_nodes\ComfyUI_InstantID\InstantID.py", line 13, in <module>
    from insightface.app import FaceAnalysis
  File "D:\ComfyUI\venv\Lib\site-packages\insightface\__init__.py", line 18, in <module>
    from . import app
  File "D:\ComfyUI\venv\Lib\site-packages\insightface\app\__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "D:\ComfyUI\venv\Lib\site-packages\insightface\app\mask_renderer.py", line 4, in <module>
    import albumentations as A
  File "D:\ComfyUI\venv\Lib\site-packages\albumentations\__init__.py", line 17, in <module>
    from .augmentations import *
  File "D:\ComfyUI\venv\Lib\site-packages\albumentations\augmentations\__init__.py", line 1, in <module>
    from .blur.functional import *
  File "D:\ComfyUI\venv\Lib\site-packages\albumentations\augmentations\blur\__init__.py", line 1, in <module>
    from .functional import *
  File "D:\ComfyUI\venv\Lib\site-packages\albumentations\augmentations\blur\functional.py", line 12, in <module>
    from albumentations.augmentations.functional import convolve
  File "D:\ComfyUI\venv\Lib\site-packages\albumentations\augmentations\functional.py", line 10, in <module>
    from albucore import (
ImportError: cannot import name 'sz_lut' from 'albucore' (D:\ComfyUI\venv\Lib\site-packages\albucore\__init__.py)

Cannot import D:\ComfyUI\custom_nodes\ComfyUI_InstantID module for custom nodes: cannot import name 'sz_lut' from 'albucore' (D:\ComfyUI\venv\Lib\site-packages\albucore\__init__.py)
```

**Comment by cubiq** [comment]
what was the last version working? this is a problem with insightface I guess

**Comment by EnragedAntelope** [comment]
Hi, not sure of which version was the latest working but I again updated albumentations and albucore and the error is gone. No further issue, thank you.
