### ISSUE TITLE
Doesn't work with other IPAdapters

### ISSUE THREAD

**Issue by JoeNavark** [cubiq/ComfyUI_InstantID#4]
The model works fine by itself, but when I have another ipadapter ahead of it I get this:

ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI_InstantID\InstantID.py", line 401, in apply_instantid
    set_model_patch_replace(work_model, patch_kwargs, ("input", id, index))
  File "D:\ComfyUI\custom_nodes\ComfyUI_InstantID\InstantID.py", line 204, in set_model_patch_replace
    to["patches_replace"]["attn2"][key].set_new_condition(**patch_kwargs)
TypeError: CrossAttentionPatch.set_new_condition() got an unexpected keyword argument 'instantid'

**Comment by cubiq** [comment]
should work now, you need to update both IPAdapter and InstantID
