### ISSUE TITLE
节点无法加载，update和安装节点都解决不了，求助

### ISSUE THREAD

**Issue by zhangfeifei0907** [cubiq/ComfyUI_InstantID#75]
已经把comfyui更新到最新版，但是加载base的工作流节点出错，无论是卸载了节点重新安装还是fix，都不行，请问可以怎么解决？

![image](https://github.com/cubiq/ComfyUI_InstantID/assets/12770631/e18945ad-ed4d-4beb-ba57-cec7f78de5f0)

![image](https://github.com/cubiq/ComfyUI_InstantID/assets/12770631/aa4ce66f-b776-488e-a295-e9ad175ff621)

 Execute install/(de)activation script for 'G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID'
 Collecting insightface
   Using cached insightface-0.7.3.tar.gz (439 kB)
   Installing build dependencies: started

   Installing build dependencies: finished with status 'done'
   Getting requirements to build wheel: started
   Getting requirements to build wheel: finished with status 'error'
[!]   error: subprocess-exited-with-error
[!]
[!]   Getting requirements to build wheel did not run successfully.
[!]   exit code: 1
[!]
[!]   [18 lines of output]
[!]   Traceback (most recent call last):
[!]     File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
[!]       main()
[!]     File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
[!]       json_out['return_val'] = hook(**hook_input['kwargs'])
[!]                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
[!]       return hook(config_settings)
[!]              ^^^^^^^^^^^^^^^^^^^^^
[!]     File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
[!]       return self._get_build_requires(config_settings, requirements=['wheel'])
[!]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
[!]       self.run_setup()
[!]     File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
[!]       exec(code, locals())
[!]     File "<string>", line 11, in <module>
[!]   ModuleNotFoundError: No module named 'Cython'
[!]   [end of output]
[!]
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
[!] error: subprocess-exited-with-error
[!]
[!] Getting requirements to build wheel did not run successfully.
[!] exit code: 1
[!]
[!] See above for output.
[!]
[!] note: This error originates from a subprocess, and is likely not a problem with pip.
install/(de)activation script failed: G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID

[ComfyUI-Manager] Startup script completed.

**Comment by zhangfeifei0907** [comment]
根据这个视频的操作，问题解决了。https://www.youtube.com/watch?v=vCCVxGtCyho
