### ISSUE TITLE
Nodes did not load when installing through comfyUI manager

### ISSUE THREAD

**Issue by uraniumcrystalsmaster** [cubiq/ComfyUI_InstantID#9]
When loading the graph, the following node types were not found:
ApplyInstantID
InstantIDFaceAnalysis
InstantIDModelLoader
FaceKeypointsPreprocessor

**Comment by uraniumcrystalsmaster** [comment]
Here's the error report that shows when ComfyUI launches:
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
DWPose: Onnxruntime with acceleration providers detected
Traceback (most recent call last):
  File "C:\Users\urani\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID\__init__.py", line 1, in <module>
    from .InstantID import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID\InstantID.py", line 12, in <module>
    from insightface.app import FaceAnalysis
ModuleNotFoundError: No module named 'insightface'

**Comment by cubiq** [comment]
you need to install insightface

**Comment by MOGRAINEREPORTS** [comment]
> you need to install insightface

This, also the reactornode installer.bat didn't work for me i had to install it manually using cmd and the python_embeded from the comfyui folder

**Comment by JorgeR81** [comment]
I installed InsightFace successfully, with the instructions from the Reactor node:
https://github.com/Gourieff/comfyui-reactor-node?tab=readme-ov-file#troubleshooting

There is also a video:
https://www.youtube.com/watch?v=vCCVxGtCyho
