### ISSUE TITLE
note: This error originates from a subprocess, and is likely not a problem with pip

### ISSUE THREAD

**Issue by tryagain1254** [cubiq/ComfyUI_InstantID#93]
Collecting insightface
 

 Using cached insightface-0.7.3.tar.gz (439 kB)
 

 Installing build dependencies: started
 

 Installing build dependencies: finished with status 'done'
 

 Getting requirements to build wheel: started
 

 Getting requirements to build wheel: finished with status 'error'
 

 [!]   error: subprocess-exited-with-error
[!]
 

 [!]   Getting requirements to build wheel did not run successfully.
[!]   exit code: 1
[!]
[!]   [18 lines of output]
[!]   Traceback (most recent call last):
[!]     File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
[!]       main()
 

 [!]     File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
[!]       json_out['return_val'] = hook(**hook_input['kwargs'])
[!]                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
[!]       return hook(config_settings)
[!]              ^^^^^^^^^^^^^^^^^^^^^
[!]     File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
 

 [!]       return self._get_build_requires(config_settings, requirements=['wheel'])
[!]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
[!]       self.run_setup()
[!]     File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
 

 [!]       exec(code, locals())
[!]     File "<string>", line 11, in <module>
[!]   ModuleNotFoundError: No module named 'Cython'
 

 [!]   [end of output]
[!]
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
 

 [!] error: subprocess-exited-with-error
[!]
[!] Getting requirements to build wheel did not run successfully.
[!] exit code: 1
 

 [!]
[!] See above for output.
[!]
[!] note: This error originates from a subprocess, and is likely not a problem with pip.
 

 [!]
[!] [notice] A new release of pip is available: 23.3.1 -> 24.0
[!] [notice] To update, run: D:\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip
 

 install/(de)activation script failed: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID
 

 Install: pip packages for 'D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID'
 

 Collecting insightface
 

 Using cached insightface-0.7.3.tar.gz (439 kB)
 

 Installing build dependencies: started
 

 Installing build dependencies: finished with status 'done'
 

 Getting requirements to build wheel: started
 

 Getting requirements to build wheel: finished with status 'error'
 

 [!]   error: subprocess-exited-with-error
[!]
 

 [!]   Getting requirements to build wheel did not run successfully.
[!]   exit code: 1
[!]
[!]   [18 lines of output]
[!]   Traceback (most recent call last):
[!]     File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
 

 [!]       main()
[!]     File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
[!]       json_out['return_val'] = hook(**hook_input['kwargs'])
[!]                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
[!]       return hook(config_settings)
 

 [!]              ^^^^^^^^^^^^^^^^^^^^^
[!]     File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
[!]       return self._get_build_requires(config_settings, requirements=['wheel'])
[!]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
 

 [!]       self.run_setup()
[!]     File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
[!]       exec(code, locals())
[!]     File "<string>", line 11, in <module>
 

 [!]   ModuleNotFoundError: No module named 'Cython'
[!]   [end of output]
[!]
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
 

 [!] error: subprocess-exited-with-error
[!]
[!] Getting requirements to build wheel did not run successfully.
 

 [!] exit code: 1
[!]
[!] See above for output.
[!]
[!] note: This error originates from a subprocess, and is likely not a problem with pip.
 

 [!]
[!] [notice] A new release of pip is available: 23.3.1 -> 24.0
[!] [notice] To update, run: D:\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip

**Comment by cubiq** [comment]
update pip

**Comment by tryagain1254** [comment]
Thank you, I have identified the root cause. It is not a node issue, but rather a mistake in the version of the Python interpreter. I have successfully installed it and the workflow can run, but there is a new issue that does not meet the expected requirements. The backend displays "unload clione 1". Could you please help me check what the problem is? Thank you very much
![Uploading 70829c413ba5e5024c9bce62636ae3a.png…]()

**Comment by tryagain1254** [comment]
Error occurred when executing InstantIDFaceAnalysis:

D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:857 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.


File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 155, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 85, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 78, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID\InstantID.py", line 360, in load_insight_face
model = FaceAnalysis(name="antelopev2", root=INSIGHTFACE_DIR, providers=[provider + 'ExecutionProvider',]) # buffalo_l
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\face_analysis.py", line 31, in __init__
model = model_zoo.get_model(onnx_file, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
model = router.get_model(providers=providers, provider_options=provider_options)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\model_zoo\model_zoo.py", line 40, in get_model
session = PickableInferenceSession(self.onnx_file, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
super().__init__(model_path, **kwargs)
File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 432, in __init__
raise fallback_error from e
File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 427, in __init__
self._create_inference_session(self._fallback_providers, None)
File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 483, in _create_inference_session
sess.initialize_session(providers, provider_options, disabled_optimizers)

**Comment by cubiq** [comment]
select CPU provider
